package jetbrains.mps.langvisualization.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.backports.LinkedList;

public enum PackageMapping {
  none("none", "none"),
  vpack("virtualpackage", "vpack"),
  lang("language", "lang");

  private String myName;
  public String getName() {
    return this.myName;
  }
  public String getValueAsString() {
    return this.myValue;
  }
  public static List<PackageMapping> getConstants() {
    List<PackageMapping> list = ListSequence.fromList(new LinkedList<PackageMapping>());
    ListSequence.fromList(list).addElement(PackageMapping.none);
    ListSequence.fromList(list).addElement(PackageMapping.vpack);
    ListSequence.fromList(list).addElement(PackageMapping.lang);
    return list;
  }
  public static PackageMapping getDefault() {
    return PackageMapping.none;
  }
  public static PackageMapping parseValue(String value) {
    if (value == null) {
      return PackageMapping.getDefault();
    }
    if (value.equals(PackageMapping.none.getValueAsString())) {
      return PackageMapping.none;
    }
    if (value.equals(PackageMapping.vpack.getValueAsString())) {
      return PackageMapping.vpack;
    }
    if (value.equals(PackageMapping.lang.getValueAsString())) {
      return PackageMapping.lang;
    }
    return PackageMapping.getDefault();
  }
  private String myValue;
  PackageMapping(String name, String value) {
    this.myName = name;
    this.myValue = value;
  }
  public String getValue() {
    return this.myValue;
  }
}
