package jetbrains.mps.langvisualization.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class ConceptReference_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public ConceptReference_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.langvisualization.structure.ConceptReference";
  }
}
