package jetbrains.mps.langvisualization.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;
import com.mbeddr.mpsutil.plantuml.node.behavior.IVisualizable_BehaviorDescriptor;
import jetbrains.mps.lang.core.behavior.INamedConcept_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.core.behavior.INamedConcept_Behavior;
import com.mbeddr.mpsutil.plantuml.node.behavior.VisGraph;

public class LanguageVisualization_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements IVisualizable_BehaviorDescriptor, INamedConcept_BehaviorDescriptor {
  public LanguageVisualization_BehaviorDescriptor() {
  }
  public String[] virtual_getCategories_3225038607917463882(SNode thisNode) {
    return LanguageVisualization_Behavior.virtual_getCategories_3225038607917463882(thisNode);
  }
  public String virtual_getFqName_1213877404258(SNode thisNode) {
    return INamedConcept_Behavior.virtual_getFqName_1213877404258(thisNode);
  }
  public void virtual_getVisualization_3225038607917463887(SNode thisNode, String category, VisGraph graph) {
    LanguageVisualization_Behavior.virtual_getVisualization_3225038607917463887(thisNode, category, graph);
  }
  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.langvisualization.structure.LanguageVisualization";
  }
}
